stages:
  - publish
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker-compose build
    - docker push $IMAGE:web
    - docker push $IMAGE:nginx

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/demo/demo_deploy/; docker compose -f docker-compose.prod.yml pull;"
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd /var/www/demo/demo_deploy/; docker compose -f docker-compose.prod.yml up -d;"
  environment:
    name: production
    url: http://52.1.72.19
  only:
    - main
